In [1]:
import numpy as np
import pandas as pd

In [2]:
past_df = pd.read_excel('./past_pairs.xlsx')

In [3]:
past_df.fillna('',inplace=True)
past_df

              pair1            pair2           pair3       date
0        Egor Bykov        Aaron Lee      Adam Ricks 2019-08-20
1        Jack Vessa     Nathan Laird                 2019-08-20
2   Katerina Schulz   Michael Ramsey                 2019-08-20
3        Matt Hwang       Lea Balido                 2019-08-20
4       Nina Nguyen   Simon Bunieski                 2019-08-20
5     Zoe Dashdavaa        Linh Chau                 2019-08-20
6   Robert Faltisco        Eric Wang                 2019-08-20
7     Anna Gadiraju        Elaine Wu                 2019-08-20
8          Brian Hu      Kenny Yeung                 2019-08-20
9   Katerina Schulz     Nathan Laird       Eric Wang 2019-08-21
10       Jack Vessa        Aaron Lee                 2019-08-21
11       Adam Ricks      Kenny Yeung                 2019-08-21
12       Matt Hwang   Michael Ramsey                 2019-08-21
13      Nina Nguyen       Lea Balido                 2019-08-21
14    Zoe Dashdavaa   Simon Bunieski                 2019-08-21
15  Robert Faltisco        Linh Chau                 2019-08-21
16    Anna Gadiraju       Egor Bykov                 2019-08-21
17         Brian Hu        Elaine Wu                 2019-08-21
18       Adam Ricks        Elaine Wu      Lea Balido 2019-08-22
19       Egor Bykov      Kenny Yeung                 2019-08-22
20  Katerina Schulz        Aaron Lee                 2019-08-22
21       Matt Hwang    Zoe Dashdavaa                 2019-08-22
22      Nina Nguyen   Michael Ramsey                 2019-08-22
23        Linh Chau       Jack Vessa                 2019-08-22
24  Robert Faltisco     Nathan Laird                 2019-08-22
25    Anna Gadiraju        Eric Wang                 2019-08-22
26         Brian Hu   Simon Bunieski                 2019-08-22
27       Adam Ricks        Eric Wang       Linh Chau 2019-08-23
28       Egor Bykov        Elaine Wu                 2019-08-23
29       Jack Vessa      Kenny Yeung                 2019-08-23
30       Matt Hwang        Aaron Lee                 2019-08-23
31      Nina Nguyen     Nathan Laird                 2019-08-23
32    Zoe Dashdavaa   Michael Ramsey                 2019-08-23
33  Robert Faltisco       Lea Balido                 2019-08-23
34    Anna Gadiraju   Simon Bunieski                 2019-08-23
35         Brian Hu  Katerina Schulz                 2019-08-23
36    Anna Gadiraju         Brian Hu  Simon Bunieski 2019-08-26
37        Eric Wang        Elaine Wu                 2019-08-26
38      Kenny Yeung       Lea Balido                 2019-08-26
39        Linh Chau   Michael Ramsey                 2019-08-26
40  Robert Faltisco     Nathan Laird                 2019-08-26
41    Zoe Dashdavaa        Aaron Lee                 2019-08-26
42       Matt Hwang       Egor Bykov                 2019-08-26
43       Jack Vessa  Katerina Schulz                 2019-08-26
44      Nina Nguyen       Adam Ricks                 2019-08-26
45    Anna Gadiraju   Michael Ramsey                 2019-08-27
46        Eric Wang       Lea Balido                 2019-08-27
47      Kenny Yeung        Elaine Wu    Nathan Laird 2019-08-27
48        Linh Chau   Simon Bunieski                 2019-08-27
49  Robert Faltisco         Brian Hu                 2019-08-27
50    Zoe Dashdavaa        Aaron Lee                 2019-08-27
51       Matt Hwang       Adam Ricks                 2019-08-27
52       Jack Vessa       Egor Bykov                 2019-08-27
53      Nina Nguyen  Katerina Schulz                 2019-08-27

In [4]:
new_df = pd.read_excel('./new_pairs.xlsx')

In [5]:
new_df.fillna('',inplace=True)
new_df.head()

             pair1           pair2 pair3 date
0    Anna Gadiraju      Lea Balido
1        Eric Wang  Michael Ramsey
2      Kenny Yeung       Aaron Lee
3        Linh Chau      Egor Bykov
4  Robert Faltisco       Elaine Wu

In [6]:
def create_pairs(df):
    pairs = set()
    trios = set()
    xPairs = set()
    for i,j,k in zip(df['pair1'], df['pair2'], df['pair3']):
        if i == '':
            continue
        if k != '':
            trios.add(frozenset([i,j,k]))
            xPairs.add(frozenset([i,j]))
            xPairs.add(frozenset([i,k]))
            xPairs.add(frozenset([k,j]))
        else:
            pairs.add(frozenset([i,j]))
    return pairs, trios, xPairs

past_pairs, past_trios, past_xPairs = create_pairs(past_df)
new_pairs, new_trios, new_xPairs = create_pairs(new_df)
past_xPairs

{frozenset({'Elaine Wu', 'Nathan Laird'}),
 frozenset({'Elaine Wu', 'Lea Balido'}),
 frozenset({'Adam Ricks', 'Lea Balido'}),
 frozenset({'Adam Ricks', 'Elaine Wu'}),
 frozenset({'Katerina Schulz', 'Nathan Laird'}),
 frozenset({'Anna Gadiraju', 'Brian Hu'}),
 frozenset({'Aaron Lee', 'Egor Bykov'}),
 frozenset({'Elaine Wu', 'Kenny Yeung'}),
 frozenset({'Anna Gadiraju', 'Simon Bunieski'}),
 frozenset({'Adam Ricks', 'Linh Chau'}),
 frozenset({'Brian Hu', 'Simon Bunieski'}),
 frozenset({'Adam Ricks', 'Eric Wang'}),
 frozenset({'Eric Wang', 'Katerina Schulz'}),
 frozenset({'Eric Wang', 'Linh Chau'}),
 frozenset({'Eric Wang', 'Nathan Laird'}),
 frozenset({'Kenny Yeung', 'Nathan Laird'}),
 frozenset({'Adam Ricks', 'Egor Bykov'}),
 frozenset({'Aaron Lee', 'Adam Ricks'})}

In [7]:
matches = past_pairs & new_pairs
if len(matches) > 0:
    print('Pairs repeat:', matches)
else:
    print('No exact pair repeat found')

No exact pair repeat found

In [8]:
matches = past_trios & new_trios
if len(matches) > 0:
    print('Trios repeat:', matches)
else:
    print('No trio repeat found')

No trio repeat found

In [9]:
matches = (past_xPairs & new_pairs) | (past_pairs & new_xPairs)
if len(matches) > 0:
    print('A pair was found in a trio:', matches)
else:
    print('No pair in trio repeat found')

No pair in trio repeat found

In [ ]:
from pairs import Pairs
pairing = Pairs()
pairing.init()

In [11]:
pairing.check_new()

No exact pair repeat found
No trio repeat found
No pair in trio repeat found